version: "3.9"

services:
  db:
    image: postgres:15
    container_name: lockbox-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: lockbox_user # change
      POSTGRES_PASSWORD: lockbox_pass # change
      POSTGRES_DB: lockbox # chgange
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

